# Generated by Django 4.2.2 on 2023-06-17 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0002_song'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='song',
            table='Song',
        ),
    ]
