# Generated by Django 4.2.2 on 2023-06-17 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0005_alter_song_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='song',
            table=None,
        ),
    ]
