# Generated by Django 4.2.2 on 2023-06-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0006_alter_song_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
